version: '3.4'

services:
  server:
    container_name: money
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/money
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    command: /docker-entrypoint.sh
    depends_on:
      - mongodb
    networks:
      - money-network

  mongodb:
    image: mongo:latest
    container_name: money-mongodb
    ports:
      - 27017:27017
    networks:
      - money-network

networks:
  money-network:
    external: true