version: '3.4'

services:
  server:
    container_name: manageyourmoney
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/manageyourmoney
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    command: /docker-entrypoint.sh
    depends_on:
      - mongodb
    networks:
      - manageyourmoney-network

  mongodb:
    image: mongo:latest
    container_name: manageyourmoney-mongodb
    ports:
      - 27017:27017
    networks:
      - manageyourmoney-network

networks:
  manageyourmoney-network:
    external: true